### PR TITLE
add .github actions

### PR DESCRIPTION
**Pull request by kshtsk**
This is actually a replacement for travis-ci config.
The pages to be configured from gh-pages branch to main, so we do not need to push from main to gh-pages.
Now we run jekyll build and rake test only on pull requests and do not have a deploy step, which was basically force push to gh-pages.

### CODE REVIEW

**Comment by kshtsk** [comment]
The former travis config is renamed to a backup file, we can get rid of it in upcoming PR.

**Comment by l-mb** [comment]
Thanks for doing the work on GitHub Actions!

I do admit that I preferred the additional layer of deploying from `main` to `gh-pages`, as additional safety when something was changing on `main` and the website stayed up until the tests passed again.

**Comment by l-mb** [comment]
Also, I'd propose to remove the Travis config with this PR directly, no need to split them into two PRs.

**Comment by kshtsk** [comment]
> Thanks for doing the work on GitHub Actions!
> 
> I do admit that I preferred the additional layer of deploying from `main` to `gh-pages`, as additional safety when something was changing on `main` and the website stayed up until the tests passed again.

The extra layer complicates workflow.

I do not get how is this additional layer helping? When we've been using it on travis is was absolutely useless, because even if you had anything in main that we did not want to get into the publishing branch, it was always forced pushed to it with next successful PR.

The existence of PR tests and review is exactly to avoid situations that something gets into main.

**Comment by kshtsk** [comment]
the travis is dropped

**Comment by kshtsk** [comment]
>  additional safety when something was changing on main and the website stayed up until the tests passed again
@l-mb elaborate on this? how is it possible to submit to main anything without tests passed in PR?
when we have something in main which is "not tested" as you say, how is it possible to force push the PR branch (which is based on main) without including those changes? please clarify the workflow you have in mind

**Comment by l-mb** [comment]
> When we have something in main which is "not tested" as you say, how is it possible to force push the PR branch (which is based on main) without including those changes? please clarify the workflow you have in mind

We've had incidents where people pushed to `main` directly, or merged PRs with "stale" status (they passed for the previous `main` status, then another PR got merged, and people merged the new PR and then a conflict showed).

It'd also allow the deploy step to do more than just "force push" (like prebuilding the site, or something, keeping the artifacts of that out of main).

I'd just want to keep the previous behaviour unless we have a good reason to change it.

**Comment by kshtsk** [comment]
> > When we have something in main which is "not tested" as you say, how is it possible to force push the PR branch (which is based on main) without including those changes? please clarify the workflow you have in mind
> 
> We've had incidents where people pushed to `main` directly, or merged PRs with "stale" status (they passed for the previous `main` status, then another PR got merged, and people merged the new PR and then a conflict showed).

So maybe uncheck `Allow force pushes` for the `main`. The same can happen if people push to 'gh-pages' directly by the way.
> 
> It'd also allow the deploy step to do more than just "force push" (like prebuilding the site, or something, keeping the artifacts of that out of main).

If you take a look at travis config, the deploy step does not do anything specific just except force push. The jekyll build and rake test are run just before the deploy, I do not see what else did it do.

In our case we have the same build and test in actions setup and if they are failed we just do not merge a PR.

> 
> I'd just want to keep the previous behaviour unless we have a good reason to change it.

I already listed good reason:
- make things simple, simple workflow, what is in the main, is what on the site
- use github features instead of inventing the wheel

If we really want to have gh-pages used, then there should push-based action. And by the way, I cannot see an official way of force pushing a branch, all I can see is the third party actions, which are not secure to use at all.

**Comment by l-mb** [comment]
>     * use github features instead of inventing the wheel

To be fair, GitHub _defaults_ to publishing GH Pages from a different branch rather than `main`. So this is apparently how it was intended. 

> If we really want to have gh-pages used, then there should push-based action. And by the way, I cannot see an official way of force pushing a branch, all I can see is the third party actions, which are not secure to use at all.

But for me, this seals it. I'd still prefer the additional branch, but if the GH Action model doesn't easily allow it, then let's switch over and we'll just have to be extra-careful with directly pushing to/editing `main`.

Thanks for the explanation!

**Review by l-mb — APPROVED** [review]

**Comment by s0nea** [comment]
I'm not sure if I can share much input here. If the merge is not easy to archive with github actions let's go with the current approach.

I'm not really sure if it's already the case but if not: can't we restrict the pushes to `main` by using branch protection rules? - I mean so that only a github actions job is able to push changes to `main` and no actual user?

**Comment by kshtsk** [comment]
> I'm not sure if I can share much input here. If the merge is not easy to archive with github actions let's go with the current approach.
> 
> I'm not really sure if it's already the case but if not: can't we restrict the pushes to `main` by using branch protection rules? - I mean so that only a github actions job is able to push changes to `main` and no actual user?

it is now enable to push to the main for all members

**Comment by kshtsk** [comment]
hm... looks gh-pages is something jekyll specific requirement... I will look into this more... still do not know if they wish be pushed to that branch manually

**Comment by kshtsk** [comment]
well let's merge this PR, and later we can create another actions to deploy to gh-pages, if needed

**Comment by kshtsk** [comment]
I am disabling force pushes to the main as well

**Comment by l-mb** [comment]
I updated the project settings to avoid direct pushes to main.

Nothing changes for people submitting changes - those go through PRs and then get merged.

**Pull request merged**
